package selectcontract08;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author karan Dahiya
 */
public class AddContact extends javax.swing.JDialog {

    private ContractController theController;

    /**
     * Creates new form AddContact
     */
    public AddContact(java.awt.Frame parent, boolean modal, ContractController controller) {
        super(parent, modal);
        initComponents();
        this.theController = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextContactID = new javax.swing.JTextField();
        jTextOrigin = new javax.swing.JTextField();
        jTextDestination = new javax.swing.JTextField();
        jTextOrder = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCancelBtn = new javax.swing.JButton();
        jSaveBtn = new javax.swing.JButton();
        jClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Contract to Database");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(199, 239, 239));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Contact ID: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Origin:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Destination:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setText("Order:");

        jTextContactID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextContactID.setBorder(null);
        jTextContactID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContactIDActionPerformed(evt);
            }
        });

        jTextOrigin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextOrigin.setBorder(null);
        jTextOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOriginActionPerformed(evt);
            }
        });

        jTextDestination.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextDestination.setBorder(null);

        jTextOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextOrder.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextContactID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextContactID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Details of the Contract");

        jCancelBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jCancelBtn.setText("Cancel");
        jCancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jSaveBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jSaveBtn.setText("Save");
        jSaveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });

        jClearBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jClearBtn.setText("Clear");
        jClearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelBtn)
                    .addComponent(jSaveBtn)
                    .addComponent(jClearBtn))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextContactIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContactIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContactIDActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed
        // Get the input values
        String contractID = jTextContactID.getText().trim();
        String origin = jTextOrigin.getText().trim();
        String destination = jTextDestination.getText().trim();
        String orderItem = jTextOrder.getText().trim();

        // Check for null or blank strings
        if (contractID == null || contractID.trim().isEmpty()
                || origin == null || origin.trim().isEmpty()
                || destination == null || destination.trim().isEmpty()
                || orderItem == null || orderItem.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields must be filled out.");
            return;
        }

        // Validate Contract ID
        if (!contractID.matches("[1-9][a-zA-Z]{3}")) {
            JOptionPane.showMessageDialog(this, "Invalid Contract ID. It should be a single digit 1-9 followed by 3 letters.");
            return;
        }
        // Check if Contract ID already exists in the list
        ContractModel contractModel = new ContractModel();
        ArrayList<String> existingContractIDs = contractModel.getAllContractIDs();

        if (existingContractIDs.contains(contractID) || existingContractIDs.contains(contractID.toUpperCase())) {
            JOptionPane.showMessageDialog(this, "Contract " + contractID.toUpperCase() + " already defined.");
            return;
        }
        contractID = contractID.toUpperCase();

        // Validate origin and destination cities
        String[] validCities = {"VICTORIA", "VANCOUVER", "SEATTLE", "NANIAMO", "PRINCE GEORGE"};
        if (!Arrays.asList(validCities).contains(origin.toUpperCase()) || !Arrays.asList(validCities).contains(destination.toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Invalid Origin City. Please select a valid city.");
            return;
        }

        if (origin.toUpperCase().equals(destination.toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Origin and destination cities cannot be the same.");
            return;
        }
        if (destination.toUpperCase().equals(origin.toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Origin and destination cities cannot be the same.");
            return;
        }

        // Validate order item
        if (orderItem.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Order item cannot contain any numbers.");
            return;
        }

        if (orderItem.contains(",")) {
            JOptionPane.showMessageDialog(null, "Order item cannot contain commas.");
            return;
        }

        origin = origin.substring(0, 1).toUpperCase() + origin.substring(1).toLowerCase();
        destination = destination.substring(0, 1).toUpperCase() + destination.substring(1).toLowerCase();
        orderItem = orderItem.substring(0, 1).toUpperCase() + orderItem.substring(1).toLowerCase();

        try {
            theController.makeNewContract(contractID, origin, destination, orderItem);

            // Show success message to the user
            String successMessage = "Your Order with Contract ID(" + contractID + ") has been successfully saved.";
            JOptionPane.showMessageDialog(null, successMessage);

            dispose();

            System.out.println("Data written to file successfully.");

        } catch (IOException ex) {
            System.out.println("Error writing to file: " + ex.getMessage());
            ex.printStackTrace(); // Print the stack trace for more details
        }


    }//GEN-LAST:event_jSaveBtnActionPerformed

    private void jTextOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOriginActionPerformed

    }//GEN-LAST:event_jTextOriginActionPerformed
    // Lab 7 clear button
    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        // Clear text fields
        jTextContactID.setText("");
        jTextOrigin.setText("");
        jTextDestination.setText("");
        jTextOrder.setText("");

    }//GEN-LAST:event_jClearBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jClearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSaveBtn;
    private javax.swing.JTextField jTextContactID;
    private javax.swing.JTextField jTextDestination;
    private javax.swing.JTextField jTextOrder;
    private javax.swing.JTextField jTextOrigin;
    // End of variables declaration//GEN-END:variables

}
